version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: docker_render_db
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: Docker_Render
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    image: pasos-proyecto-docker:latest
    container_name: docker_render_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/Docker_Render
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
